Web/ArsenalFanPage.Web/Controllers/HistoryController.cs
namespace ArsenalFanPage.Web.Controllers
{
    using ArsenalFanPage.Services.Data;
    using ArsenalFanPage.Web.ViewModels.News;
    using Microsoft.AspNetCore.Mvc;

    public class HistoryController : BaseController
    {
        private readonly INewsService newsService;

        public HistoryController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        [HttpGet]
        public IActionResult News(int id = 1)
        {
            const int ItemsPerPage = 4;
            var category = "HISTORY";

            var historyNews = this.newsService.GetNews<NewsInListViewModel>(id, category, ItemsPerPage);

            var viewModel = new NewsListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumer = id,
                Count = this.newsService.GetCount(category),
                News = historyNews,
            };

            return this.View(viewModel);
        }

        public IActionResult NewsById(int id)
        {
            var news = this.newsService.GetById<SingleNewsViewModel>(id);

            return this.View(news);
        }
    }
}

Web/ArsenalFanPage.Web/Controllers/OrdersController.cs
namespace ArsenalFanPage.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;

    using ArsenalFanPage.Services.Data;
    using ArsenalFanPage.Services.Mapping;
    using ArsenalFanPage.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : BaseController
    {
        private readonly IOrderService orderService;

        public OrdersController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        [HttpGet]
        public IActionResult Cart()
        {
            var orders = this.orderService.GetAll();

            var viewModel = new OrderCartViewModel
            {
                Ordes = (IEnumerable<OrderCreateViewModel>)orders,
            };

            return this.View(viewModel);

        }
    }
}

Web/ArsenalFanPage.Web/Controllers/ProductsController.cs
namespace ArsenalFanPage.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using ArsenalFanPage.Common;
    using ArsenalFanPage.Data.Models;
    using ArsenalFanPage.Services.Data;
    using ArsenalFanPage.Web.ViewModels.Orders;
    using ArsenalFanPage.Web.ViewModels.Product;
    using ArsenalFanPage.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ProductsController : BaseController
    {
        private readonly IProductCategorieService productCategoriesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IProductService productService;
        private readonly IWebHostEnvironment environment;
        private readonly IOrderService orderService;

        public ProductsController(
            IProductCategorieService productCategoriesService,
            UserManager<ApplicationUser> userManager,
            IProductService productService,
            IWebHostEnvironment environment,
            IOrderService orderService)
        {
            this.productCategoriesService = productCategoriesService;
            this.userManager = userManager;
            this.productService = productService;
            this.environment = environment;
            this.orderService = orderService;
        }

        [HttpPost(Name = "Order")]
        public async Task<IActionResult> Order(ProductOrderInputModel input)
        {
            var orderCreateViewModel = new OrderCreateViewModel
            {
                ProductId = input.ProductId,
                Quantity = input.Quantity,
                UserId = this.userManager.GetUserId(this.User),
            };

            await this.orderService.CreateOrder(orderCreateViewModel);

            return this.Redirect("/Orders/Cart");
        }

        public IActionResult Shop(int id = 1)
        {
            const int ItemsPerPage = 8;

            var products = this.productService.GetProducts<ProductInListViewModel>(id, ItemsPerPage);

            var viewModel = new ProductListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumer = id,
                Count = this.productService.GetCount(),
                Products = products,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Create()
        {
            var categories = this.productCategoriesService.GetAll<ProductDropDownViewModel>();
            var viewModel = new ProductCreateInputModel
            {
                Categories = categories,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Create(ProductCreateInputModel input)
        {
 
            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.productService.CreateAsync(
                input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
            }

            return this.Redirect("/Products/Shop");
        }

        public IActionResult ProductById(string id)
        {
            var news = this.productService.GetById<SingleProductViewModel>(id);

            return this.View(news);
        }
    }
}

Web/ArsenalFanPage.Web/Views/Shared/_Layout.cshtml
@using ArsenalFanPage.Common;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Arsenal @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">

    <!-- CSS Libraries -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="lib/slick/slick.css" rel="stylesheet">
    <link href="lib/slick/slick-theme.css" rel="stylesheet">
    <!--bootstrap css-->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

</head>
<body style="background-color:black;">
    <div class="top-bar active">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="tb-contact">
                        <p><i class="fas fa-envelope"></i>Arsenalfans@gmail.com</p>
                        <p><i class="fas fa-phone-alt"></i>+359893004576</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="nav-bar">
        <div class="container">
            <nav class="navbar navbar-expand-md bg-dark navbar-dark">

                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">News</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="History" asp-action="News">History</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Shop">Shop</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Cart">Shopping Cart</a>
                    </li>
                </ul>
                @if (!this.User.Identity.IsAuthenticated)
                {

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Identity" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Identity" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                }
                @if (this.User.Identity.IsAuthenticated)
                {

                    <ul class="navbar-nav ml-auto">
                        @if (User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="News" asp-action="Create">Create News</a>
                            </li>

                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Create">Add Product</a>
                            </li>


                            <li class="nav-item active">
                                <a class="nav-link" asp-area="Administration" asp-controller="News" asp-action="Index">Admin Panel</a>
                            </li>

                        }

                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Identity" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                }




            </nav>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>

    </div>

    @*footer*@
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="footer-widget">
                        <h3 class="title">Get in Touch</h3>
                        <div class="contact-info">
                            <p><i class="fa fa-map-marker"></i>1632 Sofia, Bulgaria</p>
                            <p><i class="fa fa-envelope"></i>ArsenalFans@gmail.com</p>
                            <p><i class="fa fa-phone"></i>+359893004576</p>
                        </div>
                    </div>
                </div>


                <div class="col-lg-4 col-md-6">
                    <div class="footer-widget">
                        <h3 class="title">Quick Links</h3>
                        <ul>
                            <li><a href="/">News</a></li>
                            <li><a href="/History/News">History</a></li>
                            <li><a href="/Products/Shop">Shop</a></li>
                            <li><a href="/Orders/Cart">Shopping Cart</a></li>
                            <li><a href="#">Back to the top</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6">
                    <div class="footer-widget">
                        <h3 class="title">Newsletter</h3>
                        <div class="newsletter">
                            <p>
                                Coming soon...
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/slick/slick.min.js"></script>

    <environment names="Development">
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>
</html>

Web/ArsenalFanPage.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<hr />
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if(!Model.HasPreviosPage){<text>disabled</text> }">
            <a class="page-link" asp-action="News" asp-route-id="@Model.PreviosPageNumber">Previous</a>
        </li>
        @for (int i = @Model.PageNumer - 3; i < @Model.PageNumer; i++)
        {
            if (i > 0)
            {

                <li class="page-item"><a class="page-link" asp-action="News" asp-route-id="@i">@i</a></li>

            }
        }

        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumer
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumer + 1; i <= Model.PageNumer + 3; i++)
        {
            if (i <= Model.PagesCount)
            {

                <li class="page-item"><a class="page-link" asp-action="News" asp-route-id="@i">@i</a></li>

            }
        }

        <li class="page-item @if(!Model.HasNextPage){<text>disabled</text> }">
            <a class="page-link" asp-action="News" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav> 