Web/ArsenalFanPage.Web/Controllers/CommentsController.cs
namespace ArsenalFanPage.Web.Controllers
{
    using System.Threading.Tasks;

    using ArsenalFanPage.Data.Models;
    using ArsenalFanPage.Services.Data;
    using ArsenalFanPage.Web.ViewModels.Comments;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class CommentsController : BaseController
    {
        private readonly ICommentsService commentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(
            ICommentsService commentsService,
            UserManager<ApplicationUser> userManager)
        {
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CommentCreateInputModel input)
        {
            var parentId =
                input.ParentId == 0 ?
                    (int?)null :
                    input.ParentId;

            if (parentId.HasValue)
            {
                if (!this.commentsService.IsInNewsId(parentId.Value, input.NewsId))
                {
                    return this.BadRequest();
                }
            }

            var userId = this.userManager.GetUserId(this.User);
            await this.commentsService.Create(input.NewsId, userId, input.Content, parentId);
            return this.RedirectToAction("NewsById", "History", new { id = input.NewsId });
        }
    }
}

Web/ArsenalFanPage.Web/Controllers/HomeController.cs
namespace ArsenalFanPage.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;

    using ArsenalFanPage.Data;
    using ArsenalFanPage.Data.Common.Repositories;
    using ArsenalFanPage.Data.Models;
    using ArsenalFanPage.Services.Data;
    using ArsenalFanPage.Web.ViewModels;
    using ArsenalFanPage.Web.ViewModels.Category;
    using ArsenalFanPage.Web.ViewModels.Home;
    using ArsenalFanPage.Web.ViewModels.News;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        private readonly INewsService newsService;

        public HomeController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        public IActionResult Index()
        {
            var news = this.newsService.GetNews<NewsInListViewModel>();

            var viewModel = new NewsListViewModel
            {
                Count = this.newsService.GetCount(),
                News = news,
            };

            return this.View(viewModel);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

        public IActionResult NewsById(int id)
        {
            var news = this.newsService.GetById<SingleNewsViewModel>(id);

            return this.View(news);
        }

    }
}

Web/ArsenalFanPage.Web/Views/Home/Index.cshtml
@model ArsenalFanPage.Web.ViewModels.News.NewsListViewModel
@{
    ViewData["Title"] = "News";
    var topNews = Model.News.ToArray();
    var historyNews = Model.News.Where(x => x.CategoryName == "HISTORY").ToArray();
}


<body>
    <div class="top-news">
        <div class="container">
            <div class="row">
                <div class="col-md-12 tn-left">
                    <div class="row tn-slider">
                        @for (int i = 0; i < 2; i++)
                        { 
                        <div class="col-md-6">
                            <div class="tn-img w-100">
                                <img src="@topNews[i].ImageUrl" />
                                <div class="tn-title">
                                    <a asp-action="NewsById" asp-route-id="@topNews[i].Id">@topNews[i].Title</a>
                                </div>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cat-news">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>History</h2>
                    <div class="row cn-slider">
                        @for (int i = 0; i < 2; i++)
                        {
                            <div class="col-md-6">
                                <div class="cn-img">
                                    <img src="@historyNews[i].ImageUrl" />
                                    <div class="cn-title">
                                        <a asp-action="NewsById" asp-route-id="@historyNews[i].Id">@historyNews[i].Title</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="col-md-12">
                    <h2>Top-News</h2>
                    <div class="row cn-slider">

                        @for (int i = 0; i < 3; i++)
                        {
                        <div class="col-md-6">
                            @if (i % 2 == 0)
                            {
                                <div class="cn-img">
                                    <img src="@historyNews[i].ImageUrl" />
                                    <div class="cn-title">
                                        <a asp-action="NewsById" asp-route-id="@historyNews[i].Id">@historyNews[i].Title</a>
                                    </div>
                                </div>
                            }

                            @if (i % 2 != 0)
                            {
                                <div class="cn-img">
                                    <img src="@topNews[i].ImageUrl" />
                                    <div class="cn-title">
                                        <a asp-action="NewsById" asp-route-id="@topNews[i].Id">@topNews[i].Title</a>
                                    </div>
                                </div>

                            }

                        </div>
                        }
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>

Web/ArsenalFanPage.Web/Views/Home/NewsById.cshtml
@model ArsenalFanPage.Web.ViewModels.News.SingleNewsViewModel
@{
    this.ViewData["Title"] = Model.Title;
    void DisplayComments(int? parentId)
    {
        var comments = this.Model.Comments.Where(x => x.ParentId == parentId);
        if (!comments.Any())
        {
            return;
        }


        @foreach (var comment in comments)
        {
            <div class="container-fluid mt-100">
                <div class="row">
                    <div class="col-md-11">
                        <div style="background-color:white" class="card mb-4">
                            <div class="card-header">
                                <div class="media flex-wrap w-100 align-items-center">
                                    <img src="https://icon-library.com/images/small-user-icon/small-user-icon-19.jpg" class="d-block ui-w-40 rounded-circle" alt="">
                                    <div class="media-body ml-3">
                                        @comment.UserUserName
                                        <div class="text-muted small">
                                            <time datetime="@comment.CreatedOn.ToString("O")"></time>
                                        </div>
                                    </div>
                                    <div class="text-muted small ml-3">

                                        @if (this.User.Identity.IsAuthenticated)
                                        {

                                            <div class="px-4 pt-3"> <button type="button" class="btn btn-secondary" onclick="showAddCommentForm(@comment.Id)"><i class="fa fa-plus"></i>&nbsp; Answer</button> </div>
                                        }
                                    </div>
                                </div>
                            </div>
                            <div style="background-color:black" class="card-body">
                                <article>
                                    @Html.Raw(comment.SanitizedContent)
                                </article>
                                @{ DisplayComments(comment.Id); }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
}



<!-- Single News Start-->
<div class="single-news">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="sn-container">
                    <div class="sn-img">
                        <img src="@Model.ImageUrl" alt="@Model.Title" />
                    </div>
                    <div class="sn-content">
                        <h1 class="sn-title">@Model.Title</h1>
                        <hr />
                        <hr />
                        <p>
                            @Html.Raw(Model.SanitizedContent)
                        </p>
                    </div>

                </div>
            </div>
            <hr />

            @*TODO :Commets*@

            <div class="px-4 pt-3"> <button type="button" class="btn btn-primary float-right" onclick="showAddCommentForm(0)"><i class="fa fa-plus"></i>&nbsp; Comment</button> </div>

        </div>
        <hr />
    </div>
</div>

<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: ["image paste table link code media"]
    });
</script>
<div>
    <form asp-controller="Comments" asp-action="Create" method="post" id="AddCommentForm" style="display: none">
        <input type="hidden" name="NewsId" value="@this.Model.Id" />
        <input type="hidden" name="ParentId" value="0" />
        <div>
            <label for="Content"></label>
            <textarea name="Content" id="Content" class="form-control"></textarea>
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="Add comment" />
        </div>
    </form>
</div>

@section Scripts {
    <script>
        function showAddCommentForm(parentId) {
            $("#AddCommentForm input[name='ParentId']").val(parentId);
            $("#AddCommentForm").show();
            $([document.documentElement, document.body]).animate({
                scrollTop: $("#AddCommentForm").offset().top
            }, 1000);
        }


    </script>
}